### ISSUE TITLE
Mod license

### ISSUE THREAD

**Issue by ExcaliburZero** [jordan4ibanez/Hoppers#1]
Generally it isn't a good idea to license something as "public domain", as the concept of public domain varies between countries and isn't very specific.

You may want to instead have the mod use the [CC0](https://creativecommons.org/publicdomain/zero/1.0/) or [WTFPL](http://www.wtfpl.net/) licenses, both of which essentially are equivalent to placing the mod in the public domain, but are a bit more legally sound and standardized.

**Comment by jordan4ibanez** [comment]
wtfpl - updated
